POST http://localhost:3000/insertCollaboratore
Content-Type: application/json

{
  "usr": "provacollaboratore5",
  "pwd": "provacollaboratore4",
  "email": "Prova4",
  "gestoreAgenziumUsername": "gestore1"
}