POST http://localhost:3000/insertCollaboratore
Content-Type: application/json

{
  "usr": "provacollaboratore2",
  "pwd": "provacollaboratore",
  "email": "Prova",
  "GestoreAgenziumUsername": "provaAgenzia"
}