POST http://localhost:3000/gestoreAgenzia/insertCollaboratore
Content-Type: application/json

{
  "username": "provacollaboratore2",
  "password": "provacollaboratore",
  "GestoreAgenziumUsername": "provaAgenzia"
}