
POST http://localhost:3000/upload/2
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="descrizione"

Descrizione dell'annuncio
--boundary
Content-Disposition: form-data; name="prezzo"

100000
--boundary
Content-Disposition: form-data; name="dimesioni"

100
--boundary
Content-Disposition: form-data; name="citta"

Roma
--boundary
Content-Disposition: form-data; name="viaENumeroCivico"

Via Roma, 1
--boundary
Content-Disposition: form-data; name="comune"

Roma
--boundary
Content-Disposition: form-data; name="numeroDiStanze"

3
--boundary
Content-Disposition: form-data; name="piano"

2
--boundary
Content-Disposition: form-data; name="ascensore"

true
--boundary
Content-Disposition: form-data; name="classeEnergetica"

A
--boundary
Content-Disposition: form-data; name="altriServizzi"

Piscina, Giardino
--boundary
Content-Disposition: form-data; name="Categorie"

Residenziale
--boundary
Content-Disposition: form-data; name="foto"; filename="errrrori.png"
Content-Type: image/jpeg

< ../../../imgdasalvare/errrrori.png
--boundary
Content-Disposition: form-data; name="foto"; filename="Mk2.jpg"
Content-Type: image/jpeg

< ../../../imgdasalvare/Mk2.jpg
--boundary--