POST http://localhost:3000/gestoreAgenzia/insertAgenteImmobiliare
Content-Type: application/json

{
  "usr": "provaAgenzia2",
  "pwd": "provaAgenzia2",
  "email": "provaAgenzia2",
  "referente": "provaAgenzia"
}