POST http://localhost:3000/gestoreAgenzia/insertAgenteImmobiliare
Content-Type: application/json

{
  "usr": "gennaro",
  "pwd": "password",
  "email": "002genny@gmail.com",
  "referente": "gestore123"
}