POST http://localhost:3000/collaboratore/insertAgenteImmobiliare
Content-Type: application/json

{
  "usr": "provaAgenzia12",
  "pwd": "provaAgenzia",
  "email": "provaAgenzia",
  "referente": "provacollaboratore2"
}