POST http://localhost:3000/insertGestoreAgenzia
Content-Type: application/json

{
  "username": "gestore123",
  "password": "password",
  "email": "email@google.com",
  "nomeAgenzia": "agenzia",
  "indirizzoAgenzia": "indirizzo"
}